export const Emojis: { [char: string]: string } = {
  yellow_square: "🟨",
  blue_square: "🟦",
  hamster: "🐹",
  bear: "🐻",
  marg: "🍹",
  bowling: "🎳",
  pho: "🍜",
  dice: "🎲",
  pita: "🥙",
  taco: "🌮",
  beer: "🍺",
  clink: "🍻",
  highball: "🥃",
  wine: "🍷",
  bond: "🍸",
  five: "🕔",
  five_thirty: "🕠",
  six: "🕕",
  six_thirty: "🕡",
};
